# Generated by Django 5.2.6 on 2025-11-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше отображается', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Изображение поста',
                'verbose_name_plural': 'Изображения постов',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['post', 'order'], name='main_postim_post_id_10ee9c_idx')],
            },
        ),
    ]
